Initial implementation
keboola/wr-onedrive pull request #1
Opened 2020-04-06 11:56 UTC by webrouse

### Changes:
- initial implementation

2020-04-13 19:03 UTC, webrouse commented
@ondrajodas pozries na to prosim?

- je to z velkej casti podobne ako ex-onedrive
- README: https://github.com/keboola/wr-onedrive/blob/webrouse-COM-178-impl/README.md
- Testovacie prostredie `.env` ulozene v 1p: `wr-onedrive-dev-test`

2020-04-14 06:27 UTC, webrouse commented
Otestovane aj na produkcii:

![image](https://user-images.githubusercontent.com/19371734/79192837-c01b6080-7e29-11ea-835e-43818b2fa674.png)


![image](https://user-images.githubusercontent.com/19371734/79192810-b5f96200-7e29-11ea-82b7-2ca05a58600e.png)

2020-04-15 09:10 UTC, ondrajodas requested changes
Jen pár drobností jinak lgtm 👍

2020-04-15 09:10 UTC, ondrajodas commented on src/Configuration/Actions/SearchConfigDefinition.php
> +class SearchConfigDefinition extends BaseConfigDefinition
tahle definice je stejná jako `GetWorksheetsConfigDefinition` - dalo by se to sjednotit

2020-04-15 09:10 UTC, ondrajodas commented on src/Configuration/ConfigDefinition.php
> +class ConfigDefinition extends BaseConfigDefinition
ostatní definice jsou ve složce `actions` můžeš tam přesunout i tuhle?

2020-04-15 09:10 UTC, ondrajodas commented on composer.json
> +        "jakub-onderka/php-parallel-lint": "^1.0",
můžeš prosím tě tenhle balíček nahradit za `php-parallel-lint/php-parallel-lint`

2020-04-15 09:10 UTC, ondrajodas commented on src/Api/WorkbooksFinder.php
> +use Iterator;
není potřeba

2020-04-15 09:10 UTC, ondrajodas commented on src/Api/Batch/BatchRequest.php
> +use Microsoft\Graph\Graph;
není potřeba

2020-04-15 09:10 UTC, ondrajodas commented on src/Api/GraphApiFactory.php
> +        TOKEN_ENDPOINT = '/oauth2/v2.0/token',
přehoď to pls na jednořádkový definice https://keboola.slack.com/archives/C9FEAHW7N/p1586252300010900

2020-04-15 09:43 UTC, webrouse commented on src/Configuration/Actions/SearchConfigDefinition.php
> +class SearchConfigDefinition extends BaseConfigDefinition
jasne. ok.

2020-04-15 11:15 UTC, webrouse commented
@ondrajodas opravene

2020-04-16 07:25 UTC, ondrajodas approved these changes
pecka LGTM 👍

2020-04-16 07:26 UTC, merged